[package]
name = "verder-helpen-sentry"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
sentry = "0.29.1"
log = "0.4.17"
rocket = "0.5.0-rc.2"
